name: pull_request

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, reopened, labeled]
    branches:
      - master
      - 'v[0-9]+.*'

defaults:
  run:
    shell: bash

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - centos7
          - ubuntu2004
        compiler:
          - gcc-9.2
          - clang-10
        exclude:
          - os: centos7
            compiler: clang-10
    container:
      image: vesoft/nebula-dev:${{ matrix.os }}
      env:
        CCACHE_DIR: /tmp/ccache/nebula/${{ matrix.os }}-${{ matrix.compiler }}
        CCACHE_MAXSIZE: 8G
      volumes:
        - /tmp/ccache/nebula/${{ matrix.os }}-${{ matrix.compiler }}:/tmp/ccache/nebula/${{ matrix.os }}-${{ matrix.compiler }}
      options: --cap-add=SYS_PTRACE
    steps:
      - uses: actions/checkout@v2
      - name: run test
        if: ${{ matrix.compiler == 'gcc-9.2' && matrix.os == 'ubuntu2004' }}
        run: |
          pip install poetry
          poetry install
          poetry run pytest --cov my_test tests
          poetry run bash <(curl -s https://codecov.io/bash)

      - name: Send mail
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          to: harris.chu@vesoft.com
          cc: harris.chu@vesoft.com
          from: Harris
          secure: true
          body: Build job of ${{github.repository}} completed failed!
          # html_body: file://README.html
          ignore_cert: true
          convert_markdown: true