name: test

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, reopened, labeled]
    branches:
      - master
      - 'v[0-9]+.*'

defaults:
  run:
    shell: bash

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          git clone https://github.com/bamboo1021/myrepo.git
          cd myrepo && ls